### ISSUE TITLE
Changes for Tesseract 5.0

### ISSUE THREAD

**Issue by Sicos1977** [Sicos1977/TesseractOCR#1]
Placeholder for any new discussions

**Comment by fasteddys** [comment]
Hello, this is great!!!!!! 🥇 exactly what I was looking for 😄 

- [ ] Can we get and ASP MVC Core 6 sample. I was struggling with charles to get his working on core 6.
- [ ] Also, does this handle both images and pdf
- [ ] can it detect layout, perform autorotate

**Comment by Sicos1977** [comment]
If you want to get text from a PDF you can use all kind of pdf text extraction libraries. If the PDF is image based you can use something like Ghostscript. It has tesseract build in.

Also I'm still busy with development on the fork of Charles Weld

**Comment by fasteddys** [comment]
Hi, I saw your comment earlier, and I am trying to work off one base lib. since yours is .NET core 6, its a great fit.
I was trying to suggest some features list, since there are many libs but few have a a good base feature set.

For e.g. people my type or send dctor hand written letter or pdf or scan and image, but send them all as a pdf. For dev. it would be nice if we can use the same object that handles to PDF OCR to extract that text from the pdf regardless of whether it was typed or scanned.

**Comment by Sicos1977** [comment]
At the moment I'm building something handy like this. Much easier to iterator through an scanned image then the way Charles did it,

```c#
                    using (var page = engine.Process(img))
                    {
                        foreach (var block in page.Blocks)
                        {
                            Debug.Print($"Block text: {block.Text}");
                            Debug.Print($"Block confidence: {block.Confidence}");

                            foreach (var paragraph in block.Paragraphs)
                            {
                                Debug.Print($"Paragraph text: {paragraph.Text}");
                                Debug.Print($"Paragraph confidence: {paragraph.Confidence}");

                                foreach (var textLine in paragraph.TextLines)
                                {
                                    Debug.Print($"Text line text: {textLine.Text}");
                                    Debug.Print($"Text line confidence: {textLine.Confidence}");

                                    foreach (var word in textLine.Words)
                                    {
                                        Debug.Print($"Word text: {word.Text}");
                                        Debug.Print($"Word confidence: {word.Confidence}");
                                        Debug.Print($"Word is from dictionary: {word.IsFromDictionary}");
                                        Debug.Print($"Word is numeric: {word.IsNumeric}");
                                        Debug.Print($"Word language: {word.Language}");

                                        foreach (var symbol in word.Symbols)
                                        {
                                            Debug.Print($"Symbol text: {symbol.Text}");
                                            Debug.Print($"Symbol confidence: {symbol.Confidence}");
                                            Debug.Print($"Symbol is superscript: {symbol.IsSuperscript}");
                                            Debug.Print($"Symbol is dropcap: {symbol.IsDropcap}");
                                        }
                                    }
                                }
                            }
                        }
```

**Comment by Sicos1977** [comment]
I released a nuget package it should work on .net 6 (could compile it without any problems)

**Comment by strobetm** [comment]
Hello, great job is already done!

I'm getting missing dependency in runtime while creating Engine on windows.
DllNotFoundException: Failed to find library 'org.sw.demo.danbloomberg.leptonica-1.82.0.dll' for platform x64

Where can I get it?

**Comment by Sicos1977** [comment]
It should be in the package directory, just search for it and copy it to the folder where your app is running

for example c:\myprogram\x64

**Comment by strobetm** [comment]
Found in user's packages folder c:\users\<user>\.nuget\packages\tesseractocr\5.0.5\x64\, placed to x64 in output bin folder, now it works.

**Comment by Sicos1977** [comment]
I have to figure out how to modify the nuget package so that they get installed in the solution when adding the package, should be possible but never did that before.
