### ISSUE TITLE
Custom language or multiple languages

### ISSUE THREAD

**Issue by Pique7** [Sicos1977/TesseractOCR#10]
I haven't found any possibility to initialize the Tesseract engine with a custom language (e.g. "doubledutch") or multiple languages (e.g. "ger+eng").

What approach do you suggest to achieve this?

**Comment by Sicos1977** [comment]
Never thought about that, I shall add an extra method to make that possible.

**Comment by Sicos1977** [comment]
Added the options to set the language manually and set multiple languages
