### ISSUE TITLE
Will you support up to date Tesseract versions?

### ISSUE THREAD

**Issue by dogukanguran** [Sicos1977/TesseractOCR#12]
Hi,

Thanks for the tremendous work. Before I start to use your version. I wonder that will you update periodically your tesseract version according to https://github.com/tesseract-ocr/tesseract account. I ask this because of your fork from Charles version.

Sorry for writing this message as issue. 

Thank you in advance.
DG

**Comment by Sicos1977** [comment]
Yes, that is the reason why I made my own package. I plan to upgrade to newer version when possible.
