### ISSUE TITLE
Page.GetIterator() method missing

### ISSUE THREAD

**Issue by kostelis** [Sicos1977/TesseractOCR#14]
Hi there, I am trying to migrate from https://github.com/charlesw/tesseract to your package. So far everything seems great, the performance is much better, but I find that ```Page.GetIterator()``` method is missing. Did you move it under some other method, or is it gone for good?

**Comment by Sicos1977** [comment]
I made the iteration C# compatible that is why the I removed the `Page.GetIterator()` method

You now can use a normal foreach to loop through all the page objects. See this examle in the read.me

https://github.com/Sicos1977/TesseractOCR#iterate-through-the-layout-of-a-page
