### ISSUE TITLE
Incorrect path to tesseract.dll in version 5.2

### ISSUE THREAD

**Issue by gladkovayuliya** [Sicos1977/TesseractOCR#17]
Hello!
I'm trying to add nuget package to my project (latest version), but getting error:  

> Could not copy the file "C:\Users\user\.nuget\packages\tesseractocr\5.2.10\x86\tesseract51.dll" because it was not found.	

I've done some exploring and it turned out that TesseractOCR.csproj has two references to tesseract.dll: first to verision 5.1 and second to version 5.2.   
I think that the former is incorrect since version 5.2 was released?

**Comment by Sicos1977** [comment]
Uh... I have to check if I did something wrong in the nuget package. It should indeed not reference tesseract51.dll anymore. Let me check

**Comment by Sicos1977** [comment]
You are right I forgot to update the includes... did update the Links :-)

![image](https://user-images.githubusercontent.com/6692947/178474777-a4393216-d071-44c2-8214-1fde7965bc9b.png)

**Comment by Sicos1977** [comment]
Did the new nuget package solve your problem?

**Comment by gladkovayuliya** [comment]
Yes, the problem is solved, thank you for quick fix!
