### ISSUE TITLE
Unable to run in Debian 10 (buster)

### ISSUE THREAD

**Issue by kobruleht** [Sicos1977/TesseractOCR#22]
I tried to run in from ASP.NET 6 MVC application in Debian 10 (buster) Linux.

Calling controller throws error

> Failed to find library 'libleptonica-1.82.0.dll.so' for platform x64

How to use this package in Debian 10 Buster?
That version is only available in bookworm (testing).

**Comment by Sicos1977** [comment]
Try renaming libleptonica-1.82.0.dll to bleptonica-1.82.0.dll.so

**Comment by FaizaNasir-FalonITcons** [comment]
Does this version of Tesseract OCR resolve the following issues

In Tesseract most of the work is done with a C++ library.
 Interoperability is not good with .Net and
 it offers poor cross-platform compatibility, including with Azure.
 It requires us to choose the bit-version of our application, meaning that we may only deploy to either 32-bit or 64-bit targets. 
Visual C++ runtimes are required for running Tesseract.

**Comment by Sicos1977** [comment]
I have no idea I never tested this on Azure, but the library has both bit version included. 32 bits and 64. It
