### ISSUE TITLE
Ability to read MultiPageTiffs from memory

### ISSUE THREAD

**Issue by washcycle** [Sicos1977/TesseractOCR#23]
Looking to use this leptonica to read multipage tiffs from memory. 

```
/*!
 * \brief   pixaReadMemMultipageTiff()
 *
 * \param[in]    data    const; multiple pages; tiff-encoded
 * \param[in]    size    size of cdata
 * \return  pixa, or NULL on error
 *
 * <pre>
 * Notes:
 *      (1) This is an O(n) read-from-memory version of pixaReadMultipageTiff().
 * </pre>
 */
PIXA *
pixaReadMemMultipageTiff(const l_uint8  *data,
                         size_t          size)
{
```

https://github.com/DanBloomberg/leptonica/blob/master/src/tiffio.c

Would we only need to update the Interop class to add this?

**Comment by Sicos1977** [comment]
I dropped support for multi-page tiff images in favor of making this library much easier to use. Just use another tool the split the tiff in seperate files first and then feed them to TesseractOCR

**Comment by washcycle** [comment]
Fair point.

Excellent idea though, I never even considered that as an option.

Regards,
Matt

**Comment by goldsam** [comment]
Can you please reconsider this? Splitting first introduces considerable overhead.

**Comment by Sicos1977** [comment]
I can add the method that is mentioned in the first post in this issue and after that you have to feed the pix object to the OCR engine.... but I'm not going to change the ocr classes because I dropped support for multi page tiffs so that this library was much easier to use.

**Comment by goldsam** [comment]
That would be great. having the ability to load a multiple page tiff and iterate through the images is all I need. I can fid the individual Images into tesseract myself.

**Comment by goldsam** [comment]
Thank you for reconsidering this!😊

**Comment by Sicos1977** [comment]
I'll try to make some time to implements it this weekend.

**Comment by Sicos1977** [comment]
Is it possible to supply me with a multi-page tiff?

**Comment by washcycle** [comment]
found this one

**Comment by goldsam** [comment]
Let me know if I can help with the implementation.

**Comment by Sicos1977** [comment]
Helps is always welcome, at the moment time is my issue. I'll try to implement the new feature in the next week. First need to finish some other work.

**Comment by goldsam** [comment]
what kind of API did you have in mind?

**Comment by Sicos1977** [comment]
Just using leptonica to split the multipage tiff in seperate PIX (image) objects and feed them into the Tesseract engine one by one.

**Comment by Sicos1977** [comment]
Sorry for the long long delay but I added this method to the Array class

```c#
        /// <summary>
        ///     Loads the multi-page tiff from the memory <paramref name="bytes"/>
        /// </summary>
        /// <param name="bytes"></param>
        /// <returns></returns>
        public static Array LoadMultiPageTiffFromMemory(byte[] bytes)
        {
            IntPtr pixaHandle;

            fixed (byte* ptr = bytes)
            {
                pixaHandle = LeptonicaApi.Native.pixaReadMemMultipageTiff(ptr, bytes.Length);
            }

            if (pixaHandle == IntPtr.Zero) throw new IOException("Failed to load multi page image from memory");

            return new Array(pixaHandle);
        }
```

You can use it like this to read a multi page tiff image from memory

```c#
        [TestMethod]
        public void CanParseMultiPageTifFromMemory()
        {
            using var engine = CreateEngine();
            var bytes = File.ReadAllBytes(TestFilePath("./processing/multi-page.tif"));
            using var pixA = TesseractOCR.Pix.Array.LoadMultiPageTiffFromMemory(bytes);
            var i = 1;

            foreach (var pix in pixA)
            {
                using (var page = engine.Process(pix))
                {
                    var text = page.Text.Trim();

                    var expectedText = $"Page {i}";
                    Assert.AreEqual(text, expectedText);
                }

                i++;
            }
        }
```
