### ISSUE TITLE
Can't Identify the content of the picture

### ISSUE THREAD

**Issue by xyyipiantian** [Sicos1977/TesseractOCR#24]
`string rtn = string.Empty;
            using var engine = new Engine(System.Environment.CurrentDirectory + (@"/tessdata"), Language.English, EngineMode.Default);
            if (!string.IsNullOrEmpty(white_list)) engine.SetVariable("tessedit_char_whitelist", white_list);
            using var img = TesseractOCR.Pix.Image.LoadFromMemory(ImageHelper.ImageToByte(bitmap));
            //#region 测试图片处理之后是否正确
            //var imgBts = ImageHelper.Bitmap2Byte(bitmap);
            //var imgStr = Convert.ToBase64String(imgBts);
            //#endregion
            var page = engine.Process(img);
            rtn += page.Text.Trim();
            return rtn;`

Can't Get this image Text 
image Base64
`iVBORw0KGgoAAAANSUhEUgAAAJYAAABGCAIAAAChXfqaAAAgAElEQVR4nO29WZBdR5oe9v1/Zp7tbrVv2AECBAGQaBIkm+zpnh5NS/IoZIUUCsWM/aCwHbblB0XYD3Y4wq9+85OXCDukFzvCT7I8tuTRWCPNeHqazSGbTRIESYCNhdhRqL1u3f0sufnh3FsoEAV2XU7MdHdEJ28kbx2cJc//5Z/5L1/mJWstDlzYAxZwB78AEHD0l3Z/gUJyceD7C0B6CH/QB1iCIRxcQKP7H/gCMiCNsZ7gFbzce0g+79xfmULgcU7nMTpIeftx7z9eIc/j9Fl4/9UnfCMID9zrv2EZ5/7CwR1YbOPKl4GDa9Q3uD95JvivaNXXXsB4pkm/8hASnPBgz47cz61BjsbBhDzESBHdAerykjGKLweFcZ7A/BX5jAehB4jG6Zk0Xi8e+/4AexAcefABau/hx+x/7MAjGf/c2mO8+xMAL+HLNz9AzSC4r4iHxjJnyI962QEfSfA0xluNfX8AcKAx7CtPPHZ7xuqy47wvO/4m5iE/dcH4Ayk9/eUg9V/e/eHgHfyBZUwOhPHmrLEgxPivPO4w9UwZcyDd7fsHxm+sgWXc+xMAsjiwkwDi8W2Ov+QyFuT7nTy+FoqhCJx3u8V7z8wAiKisywJge3MrDMNKpaKUKi/03htjhBD73v555iXTk38w1uR5rrV2Np+equ/fkcsJwvvhB/DeO2JWYl8Uy/aXp2mtjTHWWm9dvd7Y//7ew7nhU6REeTnhef1p9/67T/HeewKp/QfSYmBLGTIT82iyFQA9JQqMOxd6gifatTn21lmWeoIgBpMgJjG0nAQI3u8F23sPIAzDfe/vAE8g/9V6bWVVBioOoyiJA6H8sEeaQX9rX+e7Wqnt/dNYrbV2luJkcl8j3hgDgIiYuayHTbL7Q0L81X5gjbHWykDte36e53i6c5d1mhX7hj5q1cqwAYDWpuxSsC6Jw7J5ZTvxjSDkfQ1ea7VnksQA7zWyxR7t996XTwXg3D6i8QRL+xvU5D2R+MrxApmEAcw+IvM5ETFYQNCoCQxJPqD9IORnICnFd0Brw8EN0oHO8pmJyX39ijzPiUgIIYTYfZaFM7B2vyfs9HeYWUoppVSkGAxAgK02bKmUpBBCKTX2QOqevJjL7HDAcc4ppYioGHUQJmYwg8i70gze7TUHvD+eronEV4538n6ad8MaOdIMcvB7a6O1Z0gSEKQgAZIQElCkDhgAc84ZeMdC79elCpd5IkG022VFHAVx5Dz2nSGstbtzzRMVh2uhbbDfEyrs4Ry8gfZDwbCESFQolXTOWWu/iRZagiPeK4Fyqim/7D1YfiEga/cCFkEQKKX2zjd+PzOyjEnuK+HN7c0gCJIkCcWTEdhCF+hbaAY7uOfVDi5FaoyhAoeTI9LtM9btysGPJk4AhmFVWDzf2QZchkKAJAIBkkAEJ/ed24piKJM9o2iudEZ5jvznOvU50gJGWDomjoZ4qv1jQ5jDemKxf1f7ahGAxP6n7juQfk1YmffYIA6usIW1tqDcqMxAP3t+s9+UUoZhGCGKEZcHQ6gEcbAfhPsOpAXQA/L92rNbyvl6dH8kcMF+EH7l/kVRaK0HMm2F3Qzps+ev9leFEEEQhBxGiEKEEjJCPI2JCE+ZEWMPpJKUBdxI83a1cJANrLVa6yzLsizL87woCmi7MDFdDNJ+v2+trVQq8/PzCwsLX3P/57lh5cF22l5eXl5bW2u1Wmma5sg+/PInRuwDYbVaTZJkcnKyfOL8/PxUZWoC9V04v6aUjTfGDMh+sbmc7yekZrNZq9VmZmZmp2arqJYHxfPdPGOM1nowGPR6vU6n0+120zRtc+efffTPB+E+EBJRHMeNRmN2dnZubm5mZmZiYmKap3Y2tmbE9MTERBRFwzPH0sKMXQc2g/NwPbQ67Xa300l7PV0UH3/8sdZ5VuSDwaA76A7SNM0zq80LR4/3253WdleCjy4eefPVb3/njbdOHT5FHvxUnL6s2YMtwwIWxsAZWANn4f7FO/9Pq9VaW1tbW1tr77RtoSUrhJQHhWWDMsrlhwFHwHkCmGUoVRgGUahCKQIVW/Xf/cf/bfik45ZxDgKQIUvTvNVqbWxtrq9vbm5utlqtdpE+aG1qhiN4cr4MA5EHsLPZPHnk2OsX33jj4qUz06dCSAbHcInPyRoIWEIBGKAALPAHf/aHaZF3u93WdnOn2exs7/S63bbruEWXBfvoeTnVCSHkqDBzbOPf/f6/P1tdPLSwOF+bVxD4Gi0sLagS6k6nU6/XAfzP/+yfXJvYWsbOoNXpNZt5r+sHKTsnvCvyNIiUipRjZHGhIwcJVrIZ9TKRLp5YQs9c3rhxJD5TOTyXwiliCRYeBCYYwHnybNFZbtWnp1BBh4qczAZaf3T1j/+vP/2D++v3KxPVer2u5qROCptqhSBQYbvImWQoWBELT2St1YXzBuyb/U4o45mp+R2f3lt7aOAPzy38/f/p3zs+t3jptTfOnTnXyQcf/PTy1avX2p2etX4YDaWh4+hJsEcYR71BP7Mpx+yUNWTDMJio1qhqPn300zPnDp2Z/p0GNOu8KmowBdAB52Vw+P0Hn/3+u39ybf2hrUcPNteMIEGkwCFzNMNqmoiFD8hSWBoHu06X9369uVWtVqcb00mtRkS9fn9nZ7vdz7744T+dnVtq1OozE5NvXXztzck3ngthFEVZlpXfpZQlqJu9nfe3Pl1PemxcKHx1QtTnpybCKA5Et93ybHNb9E0/LbKByQzDS0T1JKNc1arCs4mKfqhz2AKewfzUNOkBB6L65AQUQFhvr19euXqjfeej5c8fFsvRyVoGM9CbdqApR+RUIhLH7FlYFo4lAPJE8EzkQROTjZx0RrqTtvvQAyoQqiwxVhSf7Vy/+d692meNfi9bWd9wlqempru9jFlKEShFSoZKKZaBIrG9vO6lQcX7ircKhS9yKnKbxqHMVWplytABAmk8DOAcWuuoM2phivxx89G9nYfLxSaJRnJ2LvdWZ3m/n3Z7Pd/L0M+9NvPz80SlJy2UFCxF6VvPzx3qDfrtndbq2pa3LoyjWqUaz84+Mr0+b8netuzcW7Gbd84/fi6ERFQ648xcBla63W57q0XCCzAV3htbONtn7XnQZ7+5uS4kOJYcq3rcaFSmnGQjbdt2n/eIZ4snTzUGoU/Flduf/6sP/+jG9u12kMpANaq1Tr+XDorQqPnazKHG4lwyE0XV3/6df5eFCkkETNJ5GA2TW6ev3ri6vLGy1tnsumxz0MoHOnfadHV9strMB9ubW7S1kw+yNM1nJuenpqZsvu0tfOGKNM3NwBrvrXfOHV08IhSbwOaiSJEBrpws4qhettlhGI4AADCqk4gsAAnO+qbfSm1qqtPB9Q+/QCDDMJqMKlPR9FS90lBRJNTRo0dJcCCVDFSoAhUGSkgSnKdZs7Wzsvx4ZW2102pb70IXWKsSr1yqB4O012q3ltc27j36OnPGWptlWZIkZTAsyzJoH9mwKsHWBd4FzgXWK+8k/ImZE2EcVCcryXRdJEE37681t9Z6GyzHiEkaNgXcdrpz5e7Vd669d+3hjS3Xipcqs/OzrU6bCj9fmTkxfezVE6+8fOTsUn0hCJKGXHRgASfhJUMERgQOsOdeP7ODnQftlYfbj++sP75+/8v7q4+2tjZ3pMuZqvOzU/VJnemdjaYk5bRTXiiWSgSBCEIOlFCSBVicvXDeCLfe3bi7erfTLziAEtIiB+BoaHx5wBFAgGOEFVAOsEOedl3W0t6KqAjn4oWoEi1Ozh1bWDi1cPTE/MLh+my1EjfEFAABJcEEsetIrGOzNBN6/c7KytqXX968c+feva3H9UmVOS9Isgh9YXY2t34OhKX7UjpJSqml2aWFfj5ZE5OV6my1NlOrTVWrjTgMpDjz4kkJqRB40Dq2P/zy8uq9P7t74/7ChfkxIIRLYT/duP6vL//JJ/ev9sM8rleCamy967TaixNzLx85/9aZ19964bVjOBxDAXIHGuAAIgDJYehbW28SCmPMzjSmX2icOLmwulSb/8B+/PHdwVpzJxV6ikXorPe+cN5bq1N95sTpepDMVWeWZhaWZhcWpucneSJAvIqdHfQu3/7k3qPbnVY7mYrDOPJ6GA8qUbTljEAACXRz1BRk0O31Q64fmjw6GYhDh4//l//Z31ZMiYgaCCdRaSCIIRjOgv1+vmANR0SZiKy4S6dfuTN54ovk+o3NOz9eudxMe9KhUZ8UQhhjvg5CY0w5hBZFURq4r5x75Vtn/kZeUY0oqqmohiABKYBhBdjBGjgNF6G6MbMzFVxVWtIzXI+v6zTwfeT308dXVq6tFuuVxbqoBu2smz7uV4LKsYVjb55/7dvHLh3HoQrixCsAgpQZeZ8SEBBAAIqtzz1JBSPRiJNK48Wa7/t22ud4/eFgYyfN07U1LrzSWJpdfOn4md/9a3+/gqCKuI64gkiABbiAm8NkDY1HUw+sNmm/nzTCUKqCufQehkFdwA4zvwwZQwNROFk99Pal700cOibrlUNHTzQwUbYwBCIgBhTAgAUMfBl/cN45B++t976hKnsl89LMmVPfOf6bsr/2+9vX1m42282kXq/H1Zz1z4GwHELzPBdCRFH07W+97usT+UheASDhCKZA2mxvW7YyCUIRayBxyUJ14djM8YHfx+l5PoQuQ/Fl6/5qupHHttEINNtuq9fv9Y6dOnr6+AsXj728hPkICr0COSGS/U7fKkQsFQHeWmu8LpwzHHI4WRVSOl/UKDihDnWPdh60V9dzo8Qgtz3jWBGFYTg9Mbs0u3QEhyJwDBGCJbx2gyLVXSqCZDaHC1my83BeCclEOst9qHwZHAZsGfhnwBGqE7tBiBMzp+dmXihT0uvZpgRXSApSCQcJyzKEIQkhSg0G9n6xsNrkeV4q0kSlBokKJ3/vB3/L/Lj4cHUzb/d8GAvvvg5C730JYZl8CYJgpj6xUuQyCBNAARKQYIEAkI1GxcC20Muhc5/pdkEphBU8jhY6uKvda3fX7ndML6wmFAlrDEmOK1G91pibnpvHnAAHkKQNlITH7HRlyFLaDaGWWQxy8JacEzpTYQC4hdr0XGPm7gcPu34bpGQcB8QudTubzdXgsb9gGT6AjMAhOOCAKpzD3UMHYK+NBIUsA6m892ma1sOqo6EWWgC7+SBG2tPttB/UKi4Q/XzgJdej5GQ0K4AQCD3IAsUoHJxqSIYQCEYQjrI/gmUSyeERA3gEkXxt+pXrp298ceWzXpbqvCCxX1RpKE3nFhYWpJTOuenp6SiKnHPwmA7CBhABoUdkERhIA2kReFLg0Ik6arM0R4ZXHqxWk+q4SeyZ2kyj0YiiiJlL1W80GjMzM7dv394bVg1qMcRwGHrqo8svtnXnbolrHMZlz56vzs1Nz714+kWwwiCfqE8vzR2ORESG62E9RBAikBASpEDkAAMFhBAhhMmKfrs72WhYrTdW16rVKoZ5m5EiMiwAAe8RVtT03ESSqETxfLU6FyUREAChR2BABYY+vwEsECkoARo1fvdTancPaFvooeErIQR4aXHxlVdeWZpf6Pf7Gxsb4wXYhIcC4KEceC+vhECAEhAerkwweaCk9o5TGLyIhcmwQalPi36/2bXS7+w0B+3+i4dfCJPQwVu41f56bRBN12bAgBwZAX4vaZAmTh0DOZBZWXscTidKJQa6KLKVB49gZTJRjzlsrmxs3HlYXwpqUUWCFViCJJg9wzIssYAkCEB4CA92e9g9AABLo4F0NJzushTKdy9zM+TBHtKB3aipB5RMBJAofWZo9NH3CaxzWZHn1rAUQRSOByF5KD9s0BODGhi5RmUDrQc8G0dmPMofIMARgqPx4kI0u9bb8D3LsZBeCFCv39/uNItpk0GHlSCDs8IIIdtp5gHpIL2TzgnvqEyF1SIIX7iBDW2g4hx20zQfrT/c2dyKJ+JD04tVCje2urqVTr7QOHPsjIJkkIAUYNgyXcLwXuxC6CDoCX6lLTqsR2lFuzuTjWhtGImLdjv0Xr4b9nz/Cm2sr6lSZskAB2TWapMF2sANTLEz6PVNTkqKQIwZ5qZhT9yDnwMMyIOsh3esy1dyZD1bT8aPQS+DAFUQnmmc+M6pN64t39zJO5rtbGV6dmLm7u07n17/9NzxsxfpvEQYVsIBdGEHQaVa0rrkMBlv4AXIbm0uT81Oe0GNyYkMRQF39cG1n92+XlWJE0GQeauzxKuJQ8dePXfxtSMXGSTADKahjBkAvCOwAIR7gsFTKNKTnHCpi8R7RqDR+bSLKgBZprCfohY+C2EfeZUFBIMADa2MisM4xDrSrX6nlfUHVlcqEQseVwsdgYcMERoNCmTADuwcvCddvpIRhRGFpbEodpBgZPnF2bPqEscifO/mRyvtDTGjosnKxNTkrft3/u//71/23+6/XX3TwOUwUkiNVOy69oCAEeQA21dZjLyAz2FWsP35nS8+vHplo7NeD+Nut2g212IRLjVmXjx66vULr9ZQESAuA+/gIUuKhvSKXS0k+irTd9eKKgdShhewDAcwkYNnggMNvT3HDp49OScZcP7rc4Q1zlTBJD2sk5AhG7gU5ks8eNBcb5uskBRIIvomJEQDX2piiY0BebABvIWzMB7egi1by9qyOfiaGADSyWrhZ2pHJ85Mdlrt5Y2V3kav2em1Bt3zr52/efvLP/nJD9e31h+/sXzx1MtH6XAddQWlwAwoOAkv4BjGw01MTKbQHfQ+fvjZu598cP3B7YHNfBRz34jMwPipyeqFU2cvnbt4bP5wiR+BS+qvoJL380R5SuRoiPDwz3La26UZlBIRsCBH3pYJdfIArCd4WE+wZC3gYS1gYQEQLAPP8hQ4EBl0YQZCiEhEBZxGvonWn3/609vLDwewFAeafFHsmwr7Ovx2h303TBqSBTmQBbyH9TAWsPCejRXGkhlLC8lThApyTIW1V06c16E73Xvx8sq1Tx9czY02ZFNk9zcf/uv3//jDTz46dfjUyyfP/+bCb7oh9cFZOIHhXPjF2tXVnY07j+/eXL57c/VBc9BWlbhWCci6YzNLhxcPvXD0+EunXjw1dayBeopBMMr5lTMcM8GxI36CnAf7r1ohZQf1I4kM5xCYJ1zJUQ/2I8Nn13AeZteew4pkcIqsQFGjWg4D4Nq9L37y4NP37n50L1szjCSJC2Pa2WB8LfQOcGAME+klSw0MeAmhkDOEhvfkDFtDfiwthAcwtNNPzp+YmV96E7251R/lP9ZXvrhqpT16+MjMxGRzdevzTz7+OPzJtRcu/K+t/01aKRyEd8JDeEfeebZzi3OrW2vNXktWQlmP6o0gt0U/S2MRnT1+8jde//b5hbPTmAzBAYSBTiAkpIAQnuHZg8HwgIQo/29J5IKtFLnggBleSMux4RgcQWA4jLPYM1nCD5njbogf78XPPsGOGF7scrWBEt/MWpA38Bp2AP3B6vU//OjHN3sPBmFRq9VCGdms7wZfG2B7tlAZCSLnWObEBYSHLMM0gfWCTEU7F0KjgOdcImNnx3IsyCMECHlW5JGRUsVIfrD4gzd/7+0U+Y82f/inP/zjh3fuVpPwzdfPO1M0OysiaRTwu4YGDzsCr3dXKCKtKjtZHz09v7R48cL5F4++8Nenv1dBEECGIGCA1MzG84QQWsKrUaYQhmEJgIx0COXYqVwErdDaMOgYURGi7mVSqImBmoaqQrrCxwHIE3kBAjwDcEQesFS6ElxCaJ9mO5dukS1AuamCRcBwADlknWSi3oVtw7yzeeVPr3742cNbm3EayYkEHtpnG6l0dLi6OL4WOoDhCQUog/RAWAZ5HQEq1MqETkACMAw9JnPaE2wxEGEkqzIADWAI3MNgE1s3H98YtPrH547UpBr0O1mvk/Y6g8xoMpaCfe9WqVSSWmN6YoqIorDS7xSry+s345sLcWOR5iqoJUjiWHhdUC4gVSn38u0sYAhMkK60F9kQ5UJqyVpIw5IMK8uxlgk4gdAGJbfZQ5Y2ZTn0luDtGg40IvTukjRTgwmJSoBQSBggA3QB5ZFUgKKL7vsPrv7k7mfXV+6sZs3U5acXj7TXNrs7rWqcvHTyhZdePPvLtUTUs2kWO9Vaw0PmsG10v9i4dWP57mp79frdGxzCOt1utZoba8WgWwmjidpkdeawpX0IVq1Wiw2bVtHPc611JwgGG712fat5d7URJifnj108efbC5BkBGSo56A+qYWVo6xMsww21cDRXjPUWRNgTVhQjgpQfgbc7Ljmg0FZKAcAKCALIIgEkPBWrxda/+eTdd7748PrWo6ZPOUSNBDqpyNx0VD935uwPvv9bb8y89ssFoYWtTldzFAP0bjfvf3z9syu3rj1YW2ln3agSFjpLe/1BtxOCTsydPPfCmUPHTtQXjxjmpzmkDHKddm+7ufng/qMHD+81d/Kc0ywLWyluXLvaqFTuzz7cWt9ovtB8+fj5I8FiNFG38OQcPA9ZdKNc4LjFE3swjezV4cTmWGDPgnW/ezKiWBj4zOTMUCxc4CyMg73y6LMrt67++Wcf3Hp8L5NG1eMQofDUfrS2ND1/4dzL33v7rQu184SvDXP/1RcDM0DaRvfy8ucfXP7k85s/W9tuavYyiJIwUU5O1KrzRy+8fPLMy6fPnTx0JAkbGlExNOue8qsUwjZ2Vppry48fLj9aWV17vLXZbA22vZC5dGvdrc7nnVu3bt86fe9vffdvnmqcYjjBriRE2ZGfcCCm5Z4yTP+CecRZH/r1HgSIvfGsYWjGQHpj017aCWvVDDKHa6F3e+fuv3z3D5Y3H69sLWvOq5WkGsfeOJ3lr734yoUXX37z9TeXaJ5B4ywR/ispFi7F4JPulXeuvvfpl9d2uv1wsjo9MV2N6w9u3Z+fmL/44oXvvvrmW8cvVRAoUNulxLV9ibQEn2Dh0NTCpalvpS/3L39x5b0fv/vRxtrJl07Z2Obd9PHD9S9v313d3Pakvv+mPTPzooAjuJKw+oRVN050abeUzSjxIw/AYHc+LIP1Q0U0gA5E3qjFGWwf+h42/sW7f/TDn77LIRcmQ13WOZqOk0YYJRCUiH/8e//hgjpS9tmO2+n1er9sENqPOh+/f+v9y/cvr/eblcmp2mSNQa1uq1qtnz1x9nuXvvv20dcqiGIIM8jlgMOZUOwXZezorlJBjNADFYSvnXiVdnzYiK7h5kB1CuV9NRTattzgg1tXVre3/qt/+F+Xke6Sl7VrLo5bHMET0zD0ODwG74crnkqXzGGIoTco+jKgDFjDzk+Xr//Ztct//rNPHmw8WDp1UipKXKAc18PozPzSxeOnj86dOKWWULougLMqCRu/XBA6uBvLt66v3VruPDaCJurKKLfycPnx3bX/4j/6z9966c03pr4VI4ihXFdHKo7qcfEccyNSNQCZ9VKQBA4nU4e/+9e/g7f/3v/4e9tyhxyqk5W5ubnAqO1Od+1nn+ZwHg5wCq6UEe+Jy4xR/KhBQ4vGAB7k4MsASGmiDvURbCAKC9qwzXeu/OT/eO+PP350209XD73y0iDtheDAwBQ+CPnUwtG//coPFMIMWkBJCAISNYlf4KYlDDiHwSBj8kmsiJkAD/9vf/wnrXpvcmk6z3wzbXFvkFRr3/rWt95+++2X+IwAM8gMdBSocjGJes6EnmU+jikUT+EbIfi7f/fv/C//6p+aVC+dWmqu7LQ3WouNxcpU8t///v/wj/7BfzqHmR29M6+mJWCMVVIwnBvHJnW6TEmXCTgekSvKmdDl7aY3OopDROEoqoUffv6j3//Rv/308d1+PTp25kSHzNb2Rr62uXD0xOsXL/3gwqXXJ08dRo3hTJFXg4khU2eU9vpFaiEzSEopiJgA67wbUNovsn6RgaQTTFIQhPNea13nahn7sLYIrRqmYFJQHWq/2SoIaVeBrIW1IIIPzOREI0miVpbnpjCkKZRG+F6WbnVbGXLABZIkXABGYUJJZtzIRDBcEwmC995565wGCiLrYYJGTAgBC6RbzfW19vYfvvNv1vN2x6aN2WknbTvLsyJHYb7zG3/t6PTiq8dePD55dBozITiE90TsxHCHBQwH418ohIAMJRPKaSNN0y71B2k+UIUUEBxLGTACn1NRFFOYKkchYzSXOTIC0hT1eF8dGdmE0BrW+tHSxnx+YmKyVuk2W3k2MN4EiWTl+zu9reZ6pnukbEyCYaQj5DlCwfB2LM/QDUOjRnvjcgfthYGwqe4FoQxADsbDPu48uHzt8vV7t3/0yUdyohrUkoKgB0YwDlen6nMT/8Hf/L3JoHYI0wuoxWABJoCVhJFf2U7rFzwX7l1wqLUemIE3wuTkGRySVKGgwGW+KIqRc+ylIqnkcEmeMKCvE7DR3jsTBoqYAESQMWQSBopZFwNrizioKCWzIs3ygbOGlAvgAhhZQGgL63ksg3QPjUGAvBBCkQNbUBBWLYodpF2019srX9z64pObl2/cvz/7yulOnm+1Op1OV4rgxLETFy+8+tLJs28FFxVEUBJ5wAyyYFmGjvweJ4p+yfxC8txIJgfktXEgFjJUpDRb402KfgXSwiQsgRwswYQqgQvPeNa1J5KAM65QgRgGKcGAafU2WOtIEVnrilyFVaUEwdUqSaiEgiFnAwSAJOtLW2SMsgshgwSUUAW0BTRcDpdBf9G8cf3B9Xsr95fXHz3efrzlu5OzjfZ6s6VtEtfOHT3z3Ve//db5148Fh4IhKUoyGGCCKKmrEhiBN7SYfsEQev9EEZVSiawemjucZdTcafuCKSAZhJ4LR/Lzlc8vLr2UYM4CHo6kBQhSgKwv41J4qvbw2moLHXLihwsQbYb+jS+upe1ORUpmMkXhrQ2UiAJ1/OiRukgYMOkAURUeIAk7likDAMhHQh3locxwnWJ2bedn71/94LMvP3/cXE3dwJDVk+EHd25ISg4fOnzp5LnfOv/66wvn51FNoMjLkr9jHBVMowg8JGHk7AyT0vC8qygAAAueSURBVL9ICB2Q50YKUooAxHHcoPqR+WOtpum3iyI3zpBQkgSg7LvvvZe8JQ8dmfJAAR2SAgPEnvEcMbPxhfHaDdl92NrZutG8ce3TK+12sz4xyVK4PHeFDiRXk/jFUy9Moirgs14PwQwsQwTINfbZ1eFry3CEH/6VusFqf7Npdt67+v7d5v0bK7eWWysDzigkipThsK/53Ikzv/XKt7935OI5LE1DViBQBDCiDDNIhhTIGRnggPDp2QffYN8ZUs6xTYcUugKQGsyAVF7BpN4MuWSeIy2qJDQpX4hIMyw8LEgbpAUkoSC4QmaCfIKIUa7ek42ZqUq+ITh0zrhSqaTwij67dfX0qZMvHznvEG2jrxzVRRwhHBGLhnODh3NDTq7MpMnZeuQEmSO9uf3w8+Uvbzx6vM26NldxIsyczB08ByJKpg4t5EAPRZOyQ8qS8FCEIu1VigE4VYUVVnrNlnPrAu8Ap6Xph3kHuQbrxIaoQnDRSCOpADYwGYpH+eP7rYfr/Y3/893/t227XdezMQW1RCSBJQstvnPhzbdf/o0f1N+qgwWQIq2hwuWo6QFmMAqBHCg9YCGdGm0P4b8BhJp9F1kfuYGXiBgKQA50kAK6gSoCsnCb2Cma2YlgPr2/VZ8KuEdrd79UJI8fPqHRujG4cjZ5ceg4SwBoowUAcBlw4VuXVrj/YHXVS46TKLOFd042oma++UefvvMo23jlpfNnJk/N8PQWTAVuEjIapnWcB1s4C3ZwgDcgy2EK+yB78Mlnn3zy6Wc/W73jFo5ONkI0Gt5RMm/XttuN1P7Gb//ghenXtuBDIJg7dAuZYogQJjQZ8ntYvpneq81HG6vrJnUL9dpErbp8+/75C6f9ifATfLmARQZpbO2gU5VTbhgWdffx8PO1q59cvXL/0f1t2o6nEhFMZGlvs92uoX7mpTMvHzn3n7zwDysIJayCtbAGvIGBECQEShaIHeYahwydHGY3cvtNICyAj1dvNF3X5AUEx0EIwbbQaZEHQsowiFRQWLOztf1ofV04OVObk7FLAlVUZ6XkqanpgvK7G3e7s+2iMM/SfgzRwsTpuZnZpflDj5YfLD94vN3cDFQ0Ozfd7fU7924+WF3+4OrHR48cP33m1KmTp4/z3FnMG0i3lwk4fFtqo7ecrd179PDe8sPV9bWm7/JMvV90N64/QLeHWn1iYvLUsTMXzl44fuL05c7nwg3JosIPWbJGajUl1jqPW7pTn4iPmnnrtJJhKFU+Oemku7f92K78dGpyRioucjOwWaZEwdYZ3097O9ut1fWVjWyzF+VJPFGpJVEQR3kl6dWjJKyGjRDh9a3PK7liD0f4ZvV4C7W7rP/xP/lvVnWz2+5oawKphJJwXlsTh5GD99Zpa6w2hdFWmwJpwT2IgllIKaRUSkkpVbk7z37sSd5qdoRQ09Mzc3Oz1rp2u5UklaWlxQcPHvb7vVarnaYDpYKpqcm5ufmZ2tTZ2VPSSgCOhp9y85obt252Bv1mu9XqdjJdsBRhGIow+O7f+O1PPr1y9+7dSpzMTEwWadZu7ugsP7KwVIbTdvED4LnQQaopLd/GaGusdtZ7OGc9C5JCqUBKoaQSTMJKcKPat3naT9M8NYUBQ7IkQc2tZrVeTaKkMMWgNwBjamJqsbEotnxggme3Sjp4PZ4WOkDUE5P10lQMskx6UgQWwjI0OQfrCQhIRkkUiFBFInC9bAtCM8gTnLG5Lvp5YZytVarPNkiATTdfXJj99oVLr732Wp7n77///gcffHDlnQ8uXboUiEp9ItIVnWVZtt2/u3L9uvY3Fx96GuYLyxnREQOuP8jCSEVJdWG6IWTgvTXGOav/8H//5zpLTxw9/v3vf+/0ydPLyw8//OCjL2/fDE25WykDw5o9O7BppzJwSRCqpCqEIKJyRXUYhsaYcuMKa63PPTOMpcAIdkHIqAWBiEUcx0mShGF4292uVCpJkjjnBvGgKArFinNXsDAK5NmT+2b12BBu93pbRX+73x1kA8lSGSVIWG9N0RZKBDKQgZQePisozTwKKXJjU1Powmhn7DD4xOTs4FkIA8s1SmQfakBHq0vz1fnD/87CjJq4fv1683Fzd9Od0Avl4oSDNELX25w9yAGevAN59g7wPpAZYLMszTPnvDG6KLTI9MWFE4enZ9944803LrzpAb2yXUl9Tcui2QW837M1mQMxaQnvU537ohjttqSUkkL0t1vl4ksFsIXWptC6sGZ9ecMLFqNiRK9HRERuMNBdl4WF997keZFlmXNttIL6rCFJ/pv/Nx6EDKpX6lOhVU5qa5SQMlDl4GkKLQMVBaEMFHloa4ost5anJybdkPyQA6yUCIJIKaGHnOGn5sLAckC26KTNL9d2zq2fOnrkXPDChd85437HfXzn483m5uOHjx+tPOq1e45cEia6EV3eXslLypIHwQsL773wUCx1P+v02vC+Xq0dX1w6cuTI4drUP/re75Zuggfuth40bzwS7fxYbS6uVx3geLS0YJhz11PVwBV9k5vc5AJCBCIOYla8nW+z4vI7e85NrjM9cHkOUCTCIFaBIAht8jzT2uTh7DyLMmjjbOh1kuvC5mA5PadZ/UUG0nHnQrOMwSYGGjnAMUKCMChS5CGUAwSoTLdaeIIHdAXltqnD3k0ot7iAHZJInpoLA/A8pnfyrW67V5+o1YJ6jsxbhCKIkXi4lmk/evxwa2N7kPW9xSDm9zbu94Lh7FVyrqWD8Pj2q5egrfCoRsnCzOzx6CgBEcB5m1MdxlEcVvvIttutqJpURH0HXTsyhXaz9hKmDidg8CTL5xm8u+EOj9iYpTAdPCHyINpDsi8Z0gQ20AbWwzFEeTyD16gWkD9n76evrcfdd8a0YVO4vVsela+3uzuThgagoIBy95V+/DQxwoMKZCHiZ5skwBLKAzzchYd6tqtEECK4t3q/Vq9OV2bKpUKAd/DbGAxQGYyWmvBo1aMAur5ZpbiORAx5rr5bdEx3cGJ6EQ7wHoKAp+i5ZvR9D4TWYycG7W2thi2QVVB7tv0ezoBtSb+HwXCLy+dCYME5lB2b4PFUGXMDL3Yaet+d+/YtAi6EFTAH7FUObKDcflyYfescrgcUcDwKiexuGRaMEB1NlF9ZivWEEOgYTzN0nyiihEtg1YHb75+/dv45NY+I1N+8jLk3NxyVGyk/4w7sX3sHZ+APeDaBGVLZ5y9c/UqxhALWj8iZQ4XbXfHhRlz5XfBoNxm/5zOiHJoReLuXSrgIRh30bcnBlxn6A54vAOUkHB/4in3qMdncjqGB/XbA27+Uy1Tgns0k7F9LAsmD/3iIAoKyo+ymQPd+RvSGJ6MGjz54iq9R/pgBaLhwePcKhhBg8gfVKgHnicWBtVA4oBjn52j2K+NpIZeLxP2BIcEe4R6kT0mGZH/gqYHKRIA3Tz/xOTUYwkEx+MmCsaE3SU+WinlyALvRW4gxcxVj5abYjobvA8pzv3rsJaIQgC9daRyg5uFVB4SQAR5DCqPFqjziGg3zL8CoLo/sZmcYTrLh4ZFyQxX2DAJ5Jg8atVyU54PH+tECjEuXGg7s7sDy3Kf+Br9TwcAYI7Ud80eSxsqSC/f0MhMaDY8M0NC9292XAnviqCWkYtQnS4fkya9S7LaB4Mf52bDhMsQx+uDQCfurmwsdQxMO/tDdrRwPWBQQEeSBLyAC80h9ATAclYnSoW3iAD3yEHatnl2bRozyemL0r0/ZPqNRYYz1dTRcQXHA4gGtxpDn/pPPgVsHjEw1e+AH7Ark4PcvBXFQEdCTk3d1ztITbdvdiGa3DTSCbdcyHR7dVWXs4jlGS540aZyLHI0nz/3rcXfIL+NPBw7CDlE8YCEMEwUHPX+4E8ETM8STg2dHzlOZNRx6abu+GoF39+DnkbXJeBLgpr3mD4YG/8HLuLZPuVntXyTMPR6Evy6/hOUvFBf4dfllKL+G8Fe+/BrCX/nyawh/5cv/D5k4i2ncONq2AAAAAElFTkSuQmCC`

But Using  [tesseract](https://github.com/charlesw/tesseract) can Get this Text 1812 

this is Code used Tesseract -Version 4.1.1
`
using (var engine = new TesseractEngine(AppDomain.CurrentDomain.BaseDirectory + (@"tessdata"), "eng", EngineMode.Default))
{

    var white_list = "0123456789";
    if (!string.IsNullOrEmpty(white_list)) engine.SetVariable("tessedit_char_whitelist", white_list);
    // have to load Pix via a bitmap since Pix doesn't support loading a stream.
    using (var pix = Pix.LoadFromMemory(data))
    {
        using (var page = engine.Process(pix, PageSegMode.SingleLine))
        {
            string meanConfidenceLabel = String.Format("{0:P}", page.GetMeanConfidence());

            string resultText = page.GetText();
            rtn = resultText;
        }
    }
}
`
how can i try to ?

Look forward to your reply
Thanks

**Comment by xyyipiantian** [comment]
![image](https://user-images.githubusercontent.com/48873295/201561172-1de1cf15-f846-48e0-b1e2-8e1270f142e5.png)

**Comment by Sicos1977** [comment]
Tesseract OCR is just a wrapper around Tesseract so I dan't help you if it wont recognize the digits.
