### ISSUE TITLE
Upgrade to Tesseract v5.3.0 and Leptonica 1.83.0

### ISSUE THREAD

**Issue by vsolominov** [Sicos1977/TesseractOCR#28]
Tesseract - https://github.com/tesseract-ocr/tesseract/releases/tag/5.3.0
Leptonica - https://github.com/DanBloomberg/leptonica/releases/tag/1.83.0

**Comment by Sicos1977** [comment]
I'll try to make a new nuget package today.

**Comment by Sicos1977** [comment]
A new package is available on nuget

**Comment by vsolominov** [comment]
Thanks a lot!

But there are several problems (OS Windows):
1. Now the application gives an error that the library could not be found (`Marshal.GetLastWin32Error()` returns `126`). I tried clean solution with rebuild. If I put the `leptonica-1.82.0.dll` library in the x64 or x86 folder, then the error disappears.
2. The project files contain data for copying previous libraries to the output directory and do not contain data for new libraries. Attached a patch (what I noticed). [TesseractOCR-5.3.patch](https://github.com/Sicos1977/TesseractOCR/files/10325839/TesseractOCR-5.3.patch)
3. Tests don't pass.

**Comment by Sicos1977** [comment]
I'll look into it today

**Comment by Sicos1977** [comment]
It is failing because Tesseract is still using leptonica 1.82

**Comment by Sicos1977** [comment]
I made a new nuget package with leptonica 1.82. I also made a tesseract 5.3 version with leptonica 1.83 but for some reason then all test with tiff files failes so I decided to not use that one.
