### ISSUE TITLE
Failed to find library 'org.sw.demo.danbloomberg.leptonica-1.82.0.dll' for platform x64

### ISSUE THREAD

**Issue by sou1maker** [Sicos1977/TesseractOCR#3]
Hi, I am getting the following error when I use.
I'm guessing because the x64/x86 folder is not linked to the project folder

![image](https://user-images.githubusercontent.com/58240137/158004232-17fd95c5-78ce-42cd-aa18-1c58f2e27314.png)

**Comment by sou1maker** [comment]
Both folders exist in the output directory, but they are empty

![image](https://user-images.githubusercontent.com/58240137/158004382-07c0c5e6-68ea-4c77-ac16-7d56aec758c2.png)

**Comment by Sicos1977** [comment]
You can find the needed dlls in the package directory in your solution
