### ISSUE TITLE
Problem implementing TesseractOCR after installation by nuGet

### ISSUE THREAD

**Issue by Genko71** [Sicos1977/TesseractOCR#32]
Hi to all,
i'm new in xamarin language, i would like to make an open source application using Tesseract and xamarin forms.
I'm new to app development, but I have an idea that I would like to develop using the phone's camera and TesseactOCR.

I've installed by nuGet, the package TesseractOCR in VS 2019, but when i insert the sample code it gives me error reports.

Can you help me?

Thank you in advance.

![image](https://user-images.githubusercontent.com/124817980/217628851-018d8495-ec12-4949-be65-bc46079c521e.png)

**Comment by Sicos1977** [comment]
What is the eror that you are getting?

**Comment by Genko71** [comment]
Hi Sicos1977,
the error is that, i tried your example but it seems that the package is not there, even if it is installed, as you can see the red underlined code.

**Comment by Sicos1977** [comment]
You installed it with the nuget package manager that is inside Visual Studio?

**Comment by Sicos1977** [comment]
What I see in your screenshots is that you are missing using statements that is probably the reason why it is not working. Try to add this using statement;

`using TesseractOCR;`

Just put it below `using Xamarin.Form; `

**Comment by Genko71** [comment]
Hi,
i've tried but it gives me this error : The type or namespace name 'type/namespace' could not be found (are you missing a using directive or an assembly reference?)
Yes, i've installed it with the nuget package manager that is inside Visual Studio
It appears to have no assembly under it.

![image](https://user-images.githubusercontent.com/124817980/218269254-dc7f2856-13b5-4cb0-8bff-d2154caa5395.png)
