### ISSUE TITLE
I have a issue when run on docker desktop

### ISSUE THREAD

**Issue by g243307885** [Sicos1977/TesseractOCR#33]
Error Info: Failed to find library 'libleptonica-1.83.0.dll.so' for platform x64.
Visual Studio2022
.net core 6.0

**Comment by Sicos1977** [comment]
Is the file with that extension present somewhere in the docker container? Also turn on the debug logging to see where TesseractOCR is looking to find the file.

**Comment by ccaldwell-socotra** [comment]
I was able to fix this issue by adding this to the dockerfile:

```
WORKDIR /app/x64
RUN ln -s /usr/lib/aarch64-linux-gnu/liblept.so.5 liblept.so.5
RUN ln -s /usr/lib/aarch64-linux-gnu/liblept.so.5 libleptonica-1.83.0.dll.so
```
