### ISSUE TITLE
Separate NuGet package for native libraries

### ISSUE THREAD

**Issue by vsolominov** [Sicos1977/TesseractOCR#35]
How do you look at separating the main and independent solution (Core) from the dependencies needed for a particular system during the execution of the program (Runtime)?

For example, for Windows OS, make a separate NuGet package `TesseractOCR.Windows` (or `TesseractOCR.runtime.win`), and for Linux OS, make `TesseractOCR.Linux` (or `TesseractOCR.runtime.linux`). Although, most likely, for Linux it is better to detail the system version (debian, alpine, ubuntu...).

**Comment by Sicos1977** [comment]
Isn't that a lot of work? Because you probably also need to add native compiled version of tesseract to the diferent nuget packages.

**Comment by vsolominov** [comment]
The problem with the current native libraries is that they are compiled under Windows and simple renaming (for example, for Linux - lib...dll.so) does not solve the problem. You have to compile the libraries of the required OS, or download them from the repository. But the repository (especially the official one) does not always have up-to-date versions of native libraries. Or it happens that the version of Leptonica is 1.80, and the version of Tesseract is 5.3, but the wrapper (in C #) has already been adjusted for versions 1.83 and 5.3.

**Comment by Sicos1977** [comment]
I'm open for suggestions and pull request about how to split the package. The only problem is that I don't have a Linux or MacOS system where I can compile Tesseract en Leptonica to the native versions that they need.

**Comment by gustavogmoraes** [comment]
> The problem with the current native libraries is that they are compiled under Windows and simple renaming (for example, for Linux - lib...dll.so) does not solve the problem. You have to compile the libraries of the required OS, or download them from the repository. But the repository (especially the official one) does not always have up-to-date versions of native libraries. Or it happens that the version of Leptonica is 1.80, and the version of Tesseract is 5.3, but the wrapper (in C #) has already been adjusted for versions 1.83 and 5.3.

Exact same problem here mate, wanna share knowledge or pair to solve it?
