### ISSUE TITLE
Enhancement: expose pixLinearTRC and pixBlend?

### ISSUE THREAD

**Issue by richardtallent-erm** [Sicos1977/TesseractOCR#36]
I've been using `System.Drawing` to pre-process images *before* sending them to TesseractOCR:

- Occasionally tweaking contrast;
- Sometimes, merging multiple overlapping images into one image (due to how some PDF scanners work, they create overlapping partial-page images, each with different dimensions and X/Y position on the page).

I'd love to be rid of System.Drawing for good, and I believe Leptonica supports these operations using the `pixLinearTRC` and `pixBlend` (with a "blend to black" option?), but I'm not seeing a way to call these through `TesseractOCR.Pix.Image`.

I could duplicate all the efforts you've gone through to import Leptonica here but then I'll have to potentially deal with conflicting versions, and Tesseract is my only use case for image processing like this.

Could you by chance expose these operations and their flags?

**Comment by Sicos1977** [comment]
Do you know the signatures for these methods?

**Comment by Sicos1977** [comment]
I added the blend method to the Image class

```c#
        #region Blend
        /// <summary>
        ///     Blends this image with the given <paramref name="imageToBlendWith"/>
        /// </summary>
        /// <param name="imageToBlendWith"><see cref="Image"/></param>
        /// <param name="x">origin [UL corner] of <paramref name="imageToBlendWith"/> relative to the origin of <see cref="Image"/> can be  is smaller 0</param>
        /// <param name="y">origin [UL corner] of <paramref name="imageToBlendWith"/> relative to the origin of <see cref="Image"/> can be  is smaller 0</param>
        /// <param name="fraction"></param>
        /// <returns></returns>
        public Image Blend(Image imageToBlendWith, int x, int y, float fraction)
        {
            if (imageToBlendWith == null) 
                throw new ArgumentNullException(nameof(imageToBlendWith));

            var result = LeptonicaApi.Native.pixBlend(_handle, imageToBlendWith.Handle, x, y, fraction);

            return result == IntPtr.Zero ? null : new Image(result);
        }
        #endregion
```

**Comment by Sicos1977** [comment]
The other method I can't find in the Leptonica headers

https://github.com/DanBloomberg/leptonica/blob/6c68e008a1b98226d295ee4695f2124b2a968ef5/src/allheaders.h

**Comment by richardtallent-erm** [comment]
Ah! Looks like it's called `pixContrastTRC` (though the [Leptonica docs](http://www.leptonica.org/enhancement.html) call it `pixEnhanceContrast`)

https://github.com/DanBloomberg/leptonica/blob/6c68e008a1b98226d295ee4695f2124b2a968ef5/src/enhance.c#L402

Thanks!
