### ISSUE TITLE
TesseractOCR.Pix.Image.LoadFromFile : never finishing on release ....

### ISSUE THREAD

**Issue by xNiux** [Sicos1977/TesseractOCR#39]
I have a very strange bug with function TesseractOCR.Pix.Image.LoadFromFile : 
- On debug : Perfect
- On release : Perfect
- On installation form pushing : function never finish (no error ... just .... call never teminate ...)

=> VERSION : 
- TesseractOCR : 5.3.3
- Target application : .net Framework 4.8
- Output Type : Windows Application

Have you any idea ?

**Comment by Sicos1977** [comment]
Euh I have no idea, can you turn on logging and see what that reports?

**Comment by xNiux** [comment]
Hum ... Ok, but ... How do that ?

**Comment by xNiux** [comment]
Ok, I add this command line

`                    var logger = !string.IsNullOrWhiteSpace("reports.log")
                            ? new TesseractOCR.Loggers.Stream(File.OpenWrite("reports.log"))
                            : new TesseractOCR.Loggers.Console();
`

But the report file stay empty ... Is that any command or other code ?

**Comment by xNiux** [comment]
And ... I tried to used another Tesseract nuget Package (Named Tesseract from Charles Weld), and I have exactly the same result !
