### ISSUE TITLE
Something wrong in this code

### ISSUE THREAD

**Issue by sou1maker** [Sicos1977/TesseractOCR#4]
Something wrong in this code.

I can't catch this exception, maybe because it's RuntimeDllImport

https://github.com/Sicos1977/TesseractOCR/blob/3abe128b3434f1d4675948dac6bdcc5d88d8a4ed/TesseractOCR/Layout/EnumeratorBase.cs#L220

![image](https://user-images.githubusercontent.com/58240137/158005843-d68d5401-a07f-4710-a49b-3a398f59b982.png)

**Comment by Sicos1977** [comment]
You cant catch it with a normal try catch?

**Comment by sou1maker** [comment]
> You cant catch it with a normal try catch?

yes, it can't be caught

**Comment by sou1maker** [comment]
Unable to capture, the program crashes directly here

![image](https://user-images.githubusercontent.com/58240137/158014368-c49ea576-3304-4730-9683-33edb4bd495a.png)

**Comment by sou1maker** [comment]
This is my test image
[test_img.zip](https://github.com/Sicos1977/TesseractOCR/files/8237463/test_img.zip)

**Comment by Sicos1977** [comment]
At the moment I'm trying to make a new nuget package with Tesseract 5.1 in it, I'll let you know when it is done so you could try that one.

**Comment by Sicos1977** [comment]
I just updated the code on GitHub to Tesseract 5.1, try to clone it and see if this version solves your problem.

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/TesseractOCR/commit/6419b56ceb4e7e9c1102d9fa7aace662582a4852

**Comment by Sicos1977** [comment]
I just released a new nuget package with Tesseract updated to version 5.1

**Comment by sou1maker** [comment]
Unfortunately, the error still exists

**Comment by sou1maker** [comment]
This is the program I use for testing

[ConsoleApp1.zip](https://github.com/Sicos1977/TesseractOCR/files/8237934/ConsoleApp1.zip)
g

**Comment by Sicos1977** [comment]
Can you start Tesseract.exe without any problems?

**Comment by Sicos1977** [comment]
Nevermind I think that this is your problem. You are disposing the page object and thus destroing the reference to the Blocks object.

![image](https://user-images.githubusercontent.com/6692947/158027268-7e05bb59-77ae-4e0d-925a-8855417466cf.png)

**Comment by Sicos1977** [comment]
This works without any problems:

```c#
    static void Main(string[] args)
    {
        var result = new StringBuilder();
        using var engine = new TesseractOCR.Engine(@".\", Language.English, EngineMode.Default);
        using var pix = TesseractOCR.Pix.Image.LoadFromFile(@".\test_img.png");
        using var page = engine.Process(pix);
        foreach (var block in page.Layout)
        {
            result.AppendLine($"Block confidence: {block.Confidence}");
            if (block.BoundingBox != null)
            {
                var boundingBox = block.BoundingBox.Value;
                result.AppendLine($"Block bounding box X1 '{boundingBox.X1}', Y1 '{boundingBox.Y2}', X2 " +
                                  $"'{boundingBox.X2}', Y2 '{boundingBox.Y2}', width '{boundingBox.Width}', height '{boundingBox.Height}'");
            }
            result.AppendLine($"Block text: {block.Text}");
        }
        
        Console.WriteLine(result.ToString());
    }
```

Do not dispose the object before you are done using it !!!

**Comment by Sicos1977** [comment]
I like the mange strip drawing style :-)

**Comment by Sicos1977** [comment]
If your goal is to just get the text from the page then you also can use `page.Text`

![image](https://user-images.githubusercontent.com/6692947/158027524-bb1e8660-2b52-4a32-88bd-3972a4ab1397.png)

**Comment by sou1maker** [comment]
It's my fault, thank you very much for correcting me.

**Comment by Sicos1977** [comment]
No problems, same happend to me when I started using Tesseract :-) ... it is good to make mistakes... you learn from it.

**Comment by sou1maker** [comment]
Thank you for reminding. Forgive my bad English, thanks again

**Comment by Sicos1977** [comment]
Your English is fine, I'm also not a native English talking person (I'm from the Netherlands) so I guess real English people have something to comment about me also :-)

**Comment by sou1maker** [comment]
I wrote something like this and it works fine, thanks again.

```c#
public static IEnumerable<Block> GetBlocks(string path, Language language = Language.English)
{
    // ReSharper disable once StringLiteralTypo
    var engine = new Engine(@".\trained_data", language, EngineMode.Default);
    var pix = TesseractOCR.Pix.Image.LoadFromFile(path);
    var page = engine.Process(pix);

    return page.Layout;
}

public static IEnumerable<Paragraph> GetParagraphs(string path, Language language = Language.English)
{
    var blocks = GetBlocks(path, language);
    return from block in blocks from paragraph in block.Paragraphs select paragraph;
}

public static IEnumerable<TextLine> GetTextLines(string path, Language language = Language.English)
{
    var paragraphs = GetParagraphs(path, language);
    return from paragraph in paragraphs from textLine in paragraph.TextLines select textLine;
}

public static IEnumerable<Word> GetWords(string path, Language language = Language.English)
{
    var textLines = GetTextLines(path, language);
    return from textLine in textLines from word in textLine.Words select word;
}

public static IEnumerable<Symbol> GetSymbols(string path, Language language = Language.English)
{
    var words = GetWords(path, language);
    return from word in words from symbol in word.Symbols select symbol;
}
```
