### ISSUE TITLE
Is it supported on linux/centos ?

### ISSUE THREAD

**Issue by TejasPatadiya10** [Sicos1977/TesseractOCR#41]
Hi,

Recently we have been exploring different packages that supports OCR on linux and we have came across your package.

But when we ran it to linux/centos directly we are facing errors

so we want to know whether we need to perform any additional steps to run the same in the linux/centos

**Comment by Sicos1977** [comment]
It should work because the code is written in .net core but I never tested it because I don't have any Linux. The only difference between Windows and Linux is that Linux uses the .so as extension for Tesseract so I think you somehow have to install the needed Tesseract libraries yourself because the nuget packag only has Windows DLL's in it with the .dll extension. You could try to rename them but I don't know if that works.

**Comment by Sicos1977** [comment]
You could try to ask for some help in this issue --> https://github.com/Sicos1977/TesseractOCR/issues/35

I have used Linux in the past but that is ages ago so I don't know if I'm any help to you.

**Comment by YoshiRulz** [comment]
It looks like `[RuntimeDllImport]` and the rest of InteropDotNet is a custom reimplementation of P/Invoke and is actually cross-platform. (Our codebase also has [one of these](https://github.com/TASEmulators/BizHawk/blob/ca756a2df3694fd093a32088f8084969c5a67211/src/BizHawk.BizInvoke/BizInvoker.cs#L691), pretty cool stuff.) It may be possible to have one package for both Windows and Linux just by changing these library filenames to `leptonica-1.83.0` and `tesseract53`:
https://github.com/Sicos1977/TesseractOCR/blob/c1225951128c6c6e59892ea88214eb5bfba33275/TesseractOCR/Interop/Constants.cs#L32-L33
[The implementation for Linux](https://github.com/Sicos1977/TesseractOCR/blob/c1225951128c6c6e59892ea88214eb5bfba33275/TesseractOCR/InteropDotNet/UnixLibraryLoaderLogic.cs#L109-L120) wraps the argument to `[RuntimeDllImport]` in `$"lib{p}.so"`, but doesn't remove `.dll` first (IIRC Mono's `[DllImport]` implementation is the same—very annoying). And [the implementation for Windows](https://github.com/Sicos1977/TesseractOCR/blob/c1225951128c6c6e59892ea88214eb5bfba33275/TesseractOCR/InteropDotNet/WindowsLibraryLoaderLogic.cs#L111-L116) will add back the `.dll`.

**Comment by YoshiRulz** [comment]
Uhh? Is this wontfix?
