### ISSUE TITLE
Request for patch release with update to leptonica 1.83.1

### ISSUE THREAD

**Issue by mrbastian** [Sicos1977/TesseractOCR#42]
After upgrading to 5.3, we encountered this issue in leptonica 1.83.0, which is fixed in patch 1.83.1
- https://github.com/DanBloomberg/leptonica/commit/defa6b3d3464cf7f3dcda0f152e7355c6f8bffd9

**Comment by Sicos1977** [comment]
I'll add it to my todo list for coming week, also have to fix some other bugs in some other projects.

**Comment by Sicos1977** [comment]
I just published a new package with the latest tesseract and leptonica versions
