### ISSUE TITLE
Request to change the name of libraries with native dependencies

### ISSUE THREAD

**Issue by vsolominov** [Sicos1977/TesseractOCR#43]
Hello!

I have updated NuGet package to version **5.3.5**. After I tried to run my project in Linux I got an error that **leptonica-1.83.1** library was not found. This is because the **leptonica-*.dll** library has changed its name in the new version of NuGet package. In Linux I have to download dependencies from the OS repository and make a symbolic link to those dependencies (**leptonica** and **tesseract**). But when I upgrade to a new NuGet package, I have to change the symbolic links to update the library name.

Can you tell me if it is possible to simplify the name of libraries by removing the version from their naming?
Or another option is to load dependencies without considering their version in the name (e.g. use `.StartWith()`)?

**Comment by Sicos1977** [comment]
So you want to have some kind of option to set the library names yourself?

**Comment by vsolominov** [comment]
Option 1 - remove the version in the library name:
- leptonica-1.83.1.dll => leptonica.dll,
- tesseract53.dll => tesseract.dll.

Option 2 - pass a delegate somewhere that modifies the library name in the way the consumer needs.
Option 3 - some static field with possible names of libraries to be checked.

**Comment by Sicos1977** [comment]
I'll try to see if I can make something like this this week.

**Comment by vsolominov** [comment]
Can you tell me if you managed to solve the issue from the current task? Didn't see any changes in the repository...
