### ISSUE TITLE
Words.IsValid AccessViolationException

### ISSUE THREAD

**Issue by Ephron-WL** [Sicos1977/TesseractOCR#49]
I'm using the current version of the library on Windows 11 x64.

In trying to observe the Visual Studio Locals window, which iterates the properties of the type using reflection, a `AccessViolationException` is thrown and a developer is unable to evaluate the properties of the object.  I have narrowed this down to the evaluation of  `Words.IsValid`.  I'm not sure why this occurring.  I think it has to do with `tesseract.Dict.valid_word`.

**Comment by Sicos1977** [comment]
I don't think I can do anything about this. The code is a wrapper over a C++ DLL and if for some reason that fails it is probably because it is hosted inside the visual studio process. You can check if the signature for the C++ DLL is correct and if so I see no way to solve this problem.

**Comment by Ephron-WL** [comment]
Do you see this same issue or is it just me?  If it is just my problem then you can close this comment.  If you have the same problem then I'd consider removing the property altogether to avoid this issue or through a NotImplrementException with an explanation why.  Maybe the feature cannot be reliably provided via the unmanaged library.   Anyway, thanks for your response.
