### ISSUE TITLE
Assemblies on NuGet are not Strongly Named

### ISSUE THREAD

**Issue by kirk56k** [Sicos1977/TesseractOCR#53]
I know this is a long shot, and I'll fork this and build it myself to fix this in the short term. But it would be awesome if you could Sign your assemblies so they are Strongly Named. My project must be signed for its use case, and thus all assemblies it uses must also be strongly named. I was moving from CharlesW's amazing C# wrapper for Tesseract to yours, since yours seems to be more currently maintained and seems to be more in-line with best practices. Thanks in advance either way!

[https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name](https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name)

**Comment by Sicos1977** [comment]
I stopped signing libraries that I make because as soon as you start signing thins youre whole dependency has to be signed...
