### ISSUE TITLE
Add OCR Text layer to existing PDF

### ISSUE THREAD

**Issue by DoCode** [Sicos1977/TesseractOCR#54]
Is it possible to add a OCR text layer to an existing PDF file?

Like:
- Convert source PDF to TIFF
- OCR TIFF
- Add text layer to source PDF
- Save source PDF

Results in searchable PDF.

**Comment by Sicos1977** [comment]
Yes that is by default possible. Look inside the Tesseract manual about how you need to do it. You have all kind of different output formats Like HOCR, PDF, Html, etc....
