### ISSUE TITLE
Have you tested other language?

### ISSUE THREAD

**Issue by sFisherE** [Sicos1977/TesseractOCR#55]
I fail to recognize japanse or chinese language.
but english is OK.
so I think there may be some bug.

**Comment by Sicos1977** [comment]
Did you install the correct languages? --> https://github.com/tesseract-ocr/tessdata

And did you also set the language?

I use my project with Dutch and English and they both work fine.

**Comment by sFisherE** [comment]
it looks like the tesseract recognize japanese or chinese really bad.
it is not an issue with your project.

**Comment by Sicos1977** [comment]
For a good OCR result it is very important to optimize your images before ocring
