### ISSUE TITLE
[Example] missing `result`

### ISSUE THREAD

**Issue by phigjm** [Sicos1977/TesseractOCR#56]
The `OCR a page` works fine, but the `Iterate through the layout of a page` example from the [readme](https://github.com/Sicos1977/TesseractOCR?tab=readme-ov-file) is missing the `result` object.

Can you add initialization of the `result` object to the readme as well? 

Also, the `For more examples see https://github.com/Sicos1977/TesseractOCR/wiki/examples.md` note is from the https://github.com/charlesw/tesseract project and not up to date, I think.

**Comment by Sicos1977** [comment]
The result is just a stringbuilder like this

`var result = new StringBuilder();`
