### ISSUE TITLE
Multi-Threaded Tesseract DLL Build

### ISSUE THREAD

**Issue by dotfurther** [Sicos1977/TesseractOCR#57]
Is your tesseract DLL built with single threaded execution?  Hopefully it is.
Background:
Charles Weld's build of tesseract DLL configures the DLL build for multi-threading of image processing (leptonica), etc. This makes it run slower on servers with multiple CPUs because of core affinity (also called processor affinity).
In our case, we have multiple threads of the C# engine instances and if each engine instance also uses multi-threading (like above) then it leads to lower performance on servers/VMs due to core affinity.

Thank you.

**Comment by Sicos1977** [comment]
It is build like this --> https://github.com/Sicos1977/TesseractOCR/wiki/Compling_tesseract_and_leptonica.md

The same like how Charles Weld's builds are.
