### ISSUE TITLE
Failed to add reference leptonica

### ISSUE THREAD

**Issue by agaertner** [Sicos1977/TesseractOCR#6]
Failed to add a reference upon installation via NuGet.

The installation gets reverted and canceled.

![image](https://user-images.githubusercontent.com/13819164/160255920-ded47fb3-46eb-4bd0-8879-ff92eea7ad85.png)

**Comment by RobThree** [comment]
@agaertner:

> Edit: For random internet stranger reading: The NuGet package [IronOCR](https://ironsoftware.com/csharp/ocr/) is professionally maintained and the pinnacle of Tesseract wrappers currently out there.

It's also *at least* $499 and a recurring fee of $399 yearly. Quit a difference...

**Comment by RobThree** [comment]
@Sicos1977 Wait, what? I'm not placing commercial ads; I was pointing out to @agaertner that IronOCR costs money ($499 and and additional $399 per year) as opposed to this library which is free. I wasn't placing ads, I was replying to the "Edit: For random internet stranger" part of @agaertner comment.

**Comment by Sicos1977** [comment]
@RobThree : Ow okey I thought that you were trying to sell IronOCR :-)

**Comment by RobThree** [comment]
> I thought that you were trying to sell IronOCR 

If anyone is, it's @agaertner ...?

**Comment by agaertner** [comment]
I am not affiliated with IronOCR nor did I try to avertise is. My intentions were of good nature. IronOCR is free for personal-use. However, I agree that I should have included this info.

**Comment by Sicos1977** [comment]
What I don't understand is why you get the error because I have no problems adding the package.

What kind of project do you have and what .net language version?

**Comment by Sicos1977** [comment]
Fixed in the latest nuget package
