### ISSUE TITLE
charlesw tesseract: differences

### ISSUE THREAD

**Issue by Leftyx** [Sicos1977/TesseractOCR#63]
Hi and sorry for the silly question.

I have been using Tesseract for c# from Charlesw since forever; didn't know there was an alternative.
I can see this project supports new Tesseract and Leptonica versions ... and that is a huge plus for us.

Before migrating, I wanted to investigate the differences, if there are any in term of implementation.
Syntax and support of the models is the same.

Could you please shed some light ?

**Comment by Sicos1977** [comment]
About most of the differences you can read in the readme on the main page but there are some breaking changes but if it would take you more than one hour to fix those it probably would be much. For the rest it just works exactly the same.. it is just a C# wrapper around Tesseract itself.
