### ISSUE TITLE
Convert Bitmap -> Pix

### ISSUE THREAD

**Issue by jgilbert2017** [Sicos1977/TesseractOCR#9]
I'm working with `System.Drawing.Bitmap`s that it looks like I need to convert to Pix for recognition.

I see code in `TesseractOCR.Pix.ToPixConverter.Convert` that looks like it might do the trick, but it does not seem to be included int he nuget 5.1.6.0 package (unless I'm stupid).

Please advise!

**Comment by jgilbert2017** [comment]
i don't have an image file.  It is processed in memory and never resides on disk.  charlesw had a converter.

**Comment by Sicos1977** [comment]
I dropped support for that. To make the library cross platform. But if you have a bitmap in memory then first save it to a memory stream and then load it with LoadFromMemory. It's almost the same as Charles did

**Comment by jgilbert2017** [comment]
alright, i'll give that a shot. ty.

**Comment by Sicos1977** [comment]
> `LoadFromMemory` maybe should take `offset` / `length` arguments.

You can do that when saving to a memory stream

**Comment by Sicos1977** [comment]
Supported input formats
Tesseract uses the Leptonica library to read images with one of these formats:

PNG - requires libpng, libz
JPEG - requires libjpeg / libjpeg-turbo
TIFF - requires libtiff, libz
JPEG 2000 - requires libopenjp2
GIF - requires libgif (giflib)
WebP (including animated WebP) - requires libwebp
BMP - no library required* = PNM - no library required*
Except Leptonica
I have dropped support for the Windows.Drawing.Image namespace since this only works good on Windows and not on other systems. You should be fine with Leptonica

**Comment by Sicos1977** [comment]
Where you have something like `Pix pix` it is `Pix.Image` in my case.

But what I said is that I dropped support for System.Drawing.Common because even Microsoft is not going to support it anymore in newer .NET generations

**Comment by jgilbert2017** [comment]
BitmapToPixConverter relies internals of leptonica due to PixData,BitmapHelper,PixColormap, etc so probably a non-starter.

Could you add an overload for ` TesseractOCR.Pix.Image.LoadFromMemory(ms.GetBuffer(), 0, ms.Length);`?

**Comment by Sicos1977** [comment]
You mean like this?

```c#
        #region LoadFromMemoryStream
        /// <summary>
        ///     Loads an image from a MemoryStream
        /// </summary>
        /// <param name="memoryStream">The memory stream</param>
        /// <returns></returns>
        /// <exception cref="IOException"></exception>
        public static Image LoadFromMemoryStream(MemoryStream memoryStream)
        {
            Logger.LogInformation("Loading image from memory stream");

            return LoadFromMemory(memoryStream.GetBuffer());
        }
        #endregion
```

**Comment by Sicos1977** [comment]
But if you sent me a pull request with a working test case then I'll add it into the library and make a new nuget package.

**Comment by jgilbert2017** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/pointer-related-operators#pointer-arithmetic-operators

**Comment by Sicos1977** [comment]
Okey with this.... also added an option to just use a memorystream for other people.... the more choices the better

```c#
        #region LoadFromMemory
        /// <summary>
        ///     Loads an image from a MemoryStream
        /// </summary>
        /// <param name="memoryStream">The memory stream</param>
        /// <returns><see cref="Image"/></returns>
        /// <exception cref="IOException"></exception>
        public static Image LoadFromMemory(MemoryStream memoryStream)
        {
            Logger.LogInformation("Loading image from memory stream");
            var buffer = memoryStream.GetBuffer();
            return LoadFromMemoryInternal(buffer, 0, buffer.Length);
        }

        /// <summary>
        ///     Loads an image from a byte array
        /// </summary>
        /// <param name="bytes">The byte array</param>
        /// <returns><see cref="Image"/></returns>
        /// <exception cref="IOException"></exception>
        public static Image LoadFromMemory(byte[] bytes)
        {
            Logger.LogInformation("Loading image from byte array");
            return LoadFromMemoryInternal(bytes, 0 , bytes.Length);
        }

        /// <summary>
        ///     Loads an image from a byte array
        /// </summary>
        /// <param name="bytes">The byte array</param>
        /// <param name="offset">The offset</param>
        /// <param name="length">The length</param>
        /// <returns></returns>
        /// <exception cref="ArgumentOutOfRangeException"></exception>
        public static Image LoadFromMemory(byte[] bytes, int offset, int length)
        {
            if (offset < 0 || offset > bytes.Length)
                throw new ArgumentOutOfRangeException(nameof(offset));

            if (length < 0 || length > bytes.Length)
                throw new ArgumentOutOfRangeException(nameof(length));

            return LoadFromMemoryInternal(bytes, offset, length);
        }

        #endregion

        #region LoadFromMemoryInternal
        public static Image LoadFromMemoryInternal(byte[] bytes, int offset, int length)
        {
            IntPtr handle;

            fixed (byte* ptr = bytes)
                handle = LeptonicaApi.Native.pixReadMem(ptr + offset, length);

            if (handle == IntPtr.Zero)
            {
                const string message = "Failed to load image from memory";
                Logger.LogError(message);
                throw new IOException(message);
            }

            Logger.LogInformation("Image loaded");
            return Create(handle);
        }
        #endregion
```

**Comment by Sicos1977** [comment]
You are right already added that... 

if (offset + length > bytes.Length)
                throw new ArgumentException("Offset + length is greater then the byte array length");

**Comment by Sicos1977** [comment]
If you are okey with this I'll make a new nuget package and release it.

**Comment by Sicos1977** [comment]
```c#
        /// <summary>
        ///     Loads an image from a byte array
        /// </summary>
        /// <param name="bytes">The byte array</param>
        /// <param name="offset">The offset</param>
        /// <param name="length">The length</param>
        /// <returns></returns>
        /// <exception cref="ArgumentOutOfRangeException"></exception>
        public static Image LoadFromMemory(byte[] bytes, int offset, int length)
        {
            if (offset < 0 || offset > bytes.Length)
                throw new ArgumentOutOfRangeException(nameof(offset));

            if (length < 0 || length > bytes.Length)
                throw new ArgumentOutOfRangeException(nameof(length));

            if (offset + length > bytes.Length)
                throw new ArgumentException("Offset + length is greater then the byte array length");

            return LoadFromMemoryInternal(bytes, offset, length);
        }
```

**Comment by jgilbert2017** [comment]
wtf... the `Save()` call is throwing `ObjectDisposedException`.... hmmm...
```
                    var ms = new MemoryStream();
                    bitmap.Save(ms, ImageFormat.Bmp); 
```

**Comment by jgilbert2017** [comment]
literally 2 lines.  i tested on net6 and net472.  i'm running x86.  will test x64. 

```
var ms = new MemoryStream();
bitmap.Save(ms, ImageFormat.Bmp); 
```

**Comment by Sicos1977** [comment]
I need to do something else, be back in about an our. In the meanwhile I released a new nuget package 5.1.7 it should be available in a few minutes. Won't take to long before nuget indexes it.

**Comment by jgilbert2017** [comment]
no worries.... i'll figure it out.  big thanks for the work to upgrade tesseract!  you da man!

**Comment by Sicos1977** [comment]
Thanks... just curious... in what kind of scenario are u using TesseractOCR?

**Comment by jgilbert2017** [comment]
@Sicos1977 so.... i just bailed on the memorystream stuff and refactored my code to get rid of bitmaps.  no idea why it was puking.  all is well now and your version of tesseract is working great (i've tested against 3 different packages).  thanks again!
